Feature/topics page
datopian/portal-moei pull request #7
Opened 2023-10-24 23:00 UTC by Gutts-n

Adapted paginator and loading's components colors to follow guidelines.

2023-10-25 23:39 UTC, demenech approved these changes
LGTM (but @lucasmbispo is the official reviewer)

2023-10-25 23:39 UTC, demenech commented on components/_shared/carousel/icon_card/IconCard.tsx
> +          isActive ? 'text-[gold]' : ''
![image](https://github.com/datopian/portal-moei/assets/16550934/998cad71-7c52-4105-a6c7-61e2749914a6)

IMO this shade of yellow looks bad against white backgrounds. Maybe we can make this a bit darker? CC: @lucasmbispo

2023-10-25 23:39 UTC, demenech commented on components/_shared/carousel/icon_card/IconCard.tsx
> +          isActive ? 'text-[gold]' : ''
on the other hand you could also increase the font weight

2023-10-26 11:34 UTC, lucasmbispo requested changes
LGTM, except for org image in mobile that shouldn't shrink.
Let's aim for 320px mobile
![image](https://github.com/datopian/portal-moei/assets/101370137/17e72e52-a5f3-4fbd-ac06-200c48dfaad4)

2023-10-27 10:21 UTC, demenech approved these changes
LGTM

2023-10-27 11:38 UTC, merged